# Generated by Django 3.0.3 on 2020-12-23 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('title', models.TextField()),
                ('link', models.TextField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('read_time', models.CharField(max_length=80)),
                ('num_responses', models.CharField(max_length=1000)),
                ('num_claps', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tags', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder', models.TextField()),
                ('comment', models.TextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medium.Blogs')),
            ],
            options={
                'unique_together': {('blog', 'responder', 'comment')},
            },
        ),
    ]
